name: CI flutter  pub get
on:
  push:
    paths:
    - 'FlutterApp/trip_life/**'
    - '.github/workflows/flutter_workflow.yaml'

defaults:
  run:
    working-directory: ./FlutterApp/trip_life

jobs:
  front-flutter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.10'
      - run: flutter pub get